### ISSUE TITLE
global Css Help

### ISSUE THREAD

**Issue by C0D3-M0N** [C0D3-M0N/google-search-results-page-2#1]
I need help for the global CSS

**Comment by Ha-Mundo** [comment]
Hi, 

Here Hamundo!

Let me give you some advice.

To start try to add the global setting and normalize.css.

**Comment by C0D3-M0N** [comment]
Thanks Bro!

**Comment by Ha-Mundo** [comment]
Give me a minute

**Comment by Ha-Mundo** [comment]
Now you have to add the global css in the style.css file
